export const projects = [
  {
    num: "01",
    category: "Landing Page",
    title: "Project 01",
    desc: "Hospital Landing Page Design and Development",
    stack: [{ name: "Figma" }, { name: "NextJs" }, { name: "Typescript" }],
    img: "/assets/work/thumb1.png",
    live: "",
    github: "",
  },
  {
    num: "02",
    category: "Fullstack",
    title: "Project 02",
    desc: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    stack: [{ name: "Next.Js" }, { name: "Tailwind.css" }, { name: "Node.Js" }],
    img: "/assets/work/thumb2.png",
    live: "",
    github: "",
  },
  {
    num: "03",
    category: "Frontend",
    title: "Project 03",
    desc: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    stack: [{ name: "Next.Js" }, { name: "Tailwind.css" }],
    img: "/assets/work/thumb3.png",
    live: "https://new-sindhu.vercel.app",
    github: "",
  },
];